[package]
name = "atmos"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.3"
bevy_winit = "0.17.3"
bevy-inspector-egui = "0.35.0"
csscolorparser = "0.8.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
