name = "rectangle_stack"

[stack]
count = 5
spacing = { x = 0.0, y = 4.1, z = 0.0 }
start_offset = { x = 0.0, y = 0.0, z = 0.0 }

[[parts]]
template = "entities/rectangle.3D.toml"
name_override = "stack_rect"
